"""Deterministic Claude Ads contracts and scoring engine."""

__version__ = "2.0.0"

from .contracts import ContractError, load_contract, validate_contract
from .control_registry import (
    ControlRegistry,
    RegistryEntry,
    RegistryError,
    ScoringProfile,
    load_control_registry,
)
from .adapters import Adapter, AdapterCapabilities, GenericCSVExportAdapter, MutationDisabledError
from .models import (
    AccountSnapshot,
    AttributionWindow,
    ControlDefinition,
    EvidenceRecord,
    Finding,
    MeasurementContext,
    ReportBundle,
    RunManifest,
)
from .orchestration import (
    OrchestrationError,
    OrchestrationStore,
    artifact_sha256,
    canonical_json_bytes,
    evaluate_artifact_gate,
)
from .workflow_models import (
    BrandProfile,
    CreativeBrief,
    DataLifecycle,
    ExperimentArtifact,
    GenerationManifest,
    MediaPlan,
    MonitoringBundle,
    MutationPlan,
    OrchestrationGate,
    OrchestrationResult,
    OrchestrationRun,
    OrchestrationTask,
    SetupProfile,
)
from .reporting import (
    PDFDependencyError,
    ReportRenderError,
    atomic_write_report,
    render_html,
    render_markdown,
    render_pdf,
    render_report,
    resolve_report_path,
    write_report_bundle,
)
from .product_status import ProductStatusError, evaluate_product_status
from .scoring import CATEGORY_WEIGHT_TOTAL, SEVERITY_WEIGHTS, ScoringError
from .doctor import DoctorError, run_doctor
from .audit import AuditError, run_audit
from .warehouse import (
    ApiReadPurpose,
    DirectApiReadForbiddenError,
    MetaBudgetManager,
    MetaQuerySpec,
    MetaUsageMonitor,
    MetaUsageStats,
    MetaWarehouseReadPlane,
    Provenance,
    RateBudgetExceededError,
    StaleDataError,
    WarehouseError,
    WarehouseSnapshot,
)

__all__ = [
    "CATEGORY_WEIGHT_TOTAL",
    "SEVERITY_WEIGHTS",
    "AccountSnapshot",
    "AttributionWindow",
    "Adapter",
    "AdapterCapabilities",
    "ContractError",
    "ControlRegistry",
    "ControlDefinition",
    "MeasurementContext",
    "Finding",
    "EvidenceRecord",
    "GenericCSVExportAdapter",
    "MutationDisabledError",
    "MutationPlan",
    "MonitoringBundle",
    "MediaPlan",
    "GenerationManifest",
    "ExperimentArtifact",
    "CreativeBrief",
    "DataLifecycle",
    "BrandProfile",
    "SetupProfile",
    "OrchestrationError",
    "OrchestrationGate",
    "OrchestrationResult",
    "OrchestrationRun",
    "OrchestrationStore",
    "OrchestrationTask",
    "PDFDependencyError",
    "ProductStatusError",
    "ReportRenderError",
    "ReportBundle",
    "RegistryEntry",
    "RegistryError",
    "RunManifest",
    "ScoringError",
    "ScoringProfile",
    "DoctorError",
    "run_doctor",
    "SetupError",
    "generate_setup_profile",
    "AuditError",
    "run_audit",
    "load_contract",
    "load_control_registry",
    "atomic_write_report",
    "render_html",
    "render_markdown",
    "render_pdf",
    "render_report",
    "resolve_report_path",
    "validate_contract",
    "evaluate_product_status",
    "artifact_sha256",
    "canonical_json_bytes",
    "evaluate_artifact_gate",
    "write_report_bundle",
    "ApiReadPurpose",
    "DirectApiReadForbiddenError",
    "MetaBudgetManager",
    "MetaQuerySpec",
    "MetaUsageMonitor",
    "MetaUsageStats",
    "MetaWarehouseReadPlane",
    "Provenance",
    "RateBudgetExceededError",
    "StaleDataError",
    "WarehouseError",
    "WarehouseSnapshot",
]
